name: sequencer-automation 
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - sshtunnel
  - jira
  - flower
  - celery
  - ipython
  - psycopg2
  - paramiko
  - pip:
#    - Flask==1.0.4
    - werkzeug==0.16.0
    - apache-airflow==1.10.5
    - apache-airflow[postgres]
    - Flask-Cors
    - flask-restplus

