name: sequencer-automation 
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - airflow=1.10.0
  - airflow-with-mysql
  - flask-cors
  - jira
  - flower
  - celery
  - ipython
  - mysqlclient
  - mysql-connector-python
  - paramiko
