version: 2

executors:
  machine:
      machine: true

jobs:
  build:
    working_directory: nyuad-hpc-sequencer-automation
    executor: machine
    steps:
      - checkout
      - run: bash ./build.sh